### ISSUE TITLE
TypeError: int expected instead of float

### ISSUE THREAD

**Issue by AnilBK** [openai/procgen#1]
After installation of the library as given in the blog,it gives the following error while running it.

Logs:
C:\Users\BlackMagicia>python -m procgen.interactive --env-name starpilot
Traceback (most recent call last):
  File "C:\Users\BlackMagicia\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\BlackMagicia\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\BlackMagicia\AppData\Roaming\Python\Python36\site-packages\procgen\interactive.py", line 69, in <module>
    main()
  File "C:\Users\BlackMagicia\AppData\Roaming\Python\Python36\site-packages\procgen\interactive.py", line 64, in main
    ia = ProcgenInteractive(args.vision, env_name=args.env_name, **kwargs)
  File "C:\Users\BlackMagicia\AppData\Roaming\Python\Python36\site-packages\procgen\interactive.py", line 21, in __init__
    super().__init__(env=env, sync=False, tps=15, display_info=True)
  File "C:\Users\BlackMagicia\AppData\Roaming\Python\Python36\site-packages\procgen\interactive_base.py", line 89, in __init__
    win = pyglet.window.Window(width=win_width, height=win_height)
  File "C:\Users\BlackMagicia\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 134, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Users\BlackMagicia\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\window\__init__.py", line 571, in __init__
    self._create()
  File "C:\Users\BlackMagicia\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 169, in _create
    self._client_to_window_size(self._width, self._height)
  File "C:\Users\BlackMagicia\AppData\Local\Programs\Python\Python36\lib\site-packages\pyglet\window\win32\__init__.py", line 595, in _client_to_window_size
    rect.right = width
TypeError: int expected instead of float

**Comment by christopherhesse** [comment]
This should be fixed on master, I will fix the travis build and make a new release.  Thanks for the bug report!

**Comment by christopherhesse** [comment]
New version should be published, please do `pip install --upgrade procgen` and make sure that `pip show procgen` shows `0.9.2`.

Let me know if this fixes your issue.

**Comment by AnilBK** [comment]
Yes, this fixed the issue. Thanks!
