### ISSUE TITLE
Conda errors when using procgen

### ISSUE THREAD

**Issue by LinZichuan** [openai/procgen#33]
Dear authors,

I install procgen according to the document as the following:

```bash
git clone git@github.com:openai/procgen.git
cd procgen
conda env update --name procgen --file environment.yml
conda activate procgen
pip install -e .
```
However, when I execute the following code, it always comes with errors.
```
(procgen) lizo@ML:~$ python -c "from procgen import ProcgenEnv; ProcgenEnv(num_envs=1, env_name='coinrun')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lizo/procgen/procgen/env.py", line 184, in __init__
    super().__init__(num_envs, env_name, options, **kwargs)
  File "/home/lizo/procgen/procgen/env.py", line 91, in __init__
    lib_dir = build(debug=debug)
  File "/home/lizo/procgen/procgen/build.py", line 70, in build
    conda_prefix = conda_info["active_prefix"]
KeyError: 'active_prefix'
```

**Comment by LinZichuan** [comment]
This problem can be solved by updating conda.
```
conda update conda conda-build
```
