### ISSUE TITLE
Environment doesn't exist Error

### ISSUE THREAD

**Issue by semihtasbas** [openai/procgen#78]
Hello,
I receive below error and I used your offical setup. Can you help me about it ? 

>>> import gym
>>> env = gym.make('procgen:procgen-coinrun-v0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\PC\anaconda3\envs\procgen\lib\site-packages\gym\envs\registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "C:\Users\PC\anaconda3\envs\procgen\lib\site-packages\gym\envs\registration.py", line 490, in make
    versions = self.env_specs.versions(namespace, name)
  File "C:\Users\PC\anaconda3\envs\procgen\lib\site-packages\gym\envs\registration.py", line 220, in versions
    self._assert_name_exists(namespace, name)
  File "C:\Users\PC\anaconda3\envs\procgen\lib\site-packages\gym\envs\registration.py", line 297, in _assert_name_exists
    raise error.NameNotFound(message)
gym.error.NameNotFound: Environment `procgen:procgen-coinrun` doesn't exist.

**Comment by NikEyX** [comment]
I encountered the same when I updated my entire environment today to python 3.10. Maybe the registration doesn't work properly?

Anyways, the below makes it work

    import procgen # registers env
    env = gym.make("procgen-coinrun-v0") #should work now, notice there is no more "procgen:"
