### ISSUE TITLE
Error 0x7e

### ISSUE THREAD

**Issue by Soap-Pope** [openai/procgen#82]

**Comment by Soap-Pope** [comment]
i tried to run "python -m procgen.interactive --env-name coinrun"
I get this output:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\procgen\interactive.py", line 136, in <module>
    main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\procgen\interactive.py", line 129, in main
    ia = make_interactive(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\procgen\interactive.py", line 34, in make_interactive
    env = ProcgenGym3Env(num=1, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\procgen\env.py", line 246, in __init__
    super().__init__(num, env_name, options, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\procgen\env.py", line 128, in __init__
    super().__init__(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\gym3\libenv.py", line 111, in __init__
    self._c_lib = self._ffi.dlopen(name=self._lib_path, flags=dlopen_flags)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\cffi\api.py", line 828, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\procgen\data\prebuilt\env.dll': error 0x7e

i checked my python version with the provided commands and i get an 'ok' on both. The laptop is running a fresh installed windows 10.

**Comment by Soap-Pope** [comment]
Fixed it. Apparently it needs Microsoft Visual C++ 2015.
